In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))


import pandas as pd

google_listened_to_df = pd.read_csv('C:\\Users\\alan__000\\PycharmProjects\\GoogleMusicDataAnalysis\\takeout_data\\Google Play Music\\combined_tracks.csv')

print('track list imported')

display(google_listened_to_df.head())

track list imported

,Unnamed: 0,Title,Album,Artist,Duration (ms),Rating,Play Count,Removed
0,0,(Darlin&#39;) You Know I Love You,What&#39;s Love Got To Do With It,Tina Turner,269000,0,1,NaN
1,0,(Love Is Like A) Heatwave (2016 Remastered),The Singles,Phil Collins,172000,0,2,NaN
2,0,(Mucho Mambo) Sway (Radio Edit),Clubland 90s,Shaft,206000,0,3,NaN
3,0,(Song for My) Sugar Spun Sister (Remastered),The Stone Roses,The Stone Roses,206000,0,1,NaN
4,0,(Stay Away From) The Cocaine Train,The Essential Johnny Paycheck,Johnny Paycheck,188000,0,2,NaN

In [2]:
import numpy as np

print('Total number of Tracks : {}'.format(len(google_listened_to_df)))

google_listened_to_df



display(google_listened_to_df.head())
google_listened_to_df = google_listened_to_df.sort_values('Play Count', ascending=False)
display(google_listened_to_df.head())
google_listened_to_df.to_csv('C:\\Users\\alan__000\\PycharmProjects\\GoogleMusicDataAnalysis\\takeout_data\\Google Play Music\\combined_tracks2.csv')

# cleaned_df = google_listened_to_df.filter(google_listened_to_df['Play Count'] > 10)

# len(cleaned_df)

# combined_df.sort_values('Duration (ms)', ascending=False)
print(google_listened_to_df['Duration (ms)'].mean())
# remove outliers
combined_outliers_trimmed_df = google_listened_to_df[np.abs(google_listened_to_df['Duration (ms)']-google_listened_to_df['Duration (ms)'].mean()) <= (3*google_listened_to_df['Duration (ms)'].std())]
combined_outliers_trimmed_df.sort_values('Duration (ms)', ascending=False)

print(combined_outliers_trimmed_df['Duration (ms)'].mean())

Total number of Tracks : 4998

,Unnamed: 0,Title,Album,Artist,Duration (ms),Rating,Play Count,Removed
0,0,(Darlin&#39;) You Know I Love You,What&#39;s Love Got To Do With It,Tina Turner,269000,0,1,NaN
1,0,(Love Is Like A) Heatwave (2016 Remastered),The Singles,Phil Collins,172000,0,2,NaN
2,0,(Mucho Mambo) Sway (Radio Edit),Clubland 90s,Shaft,206000,0,3,NaN
3,0,(Song for My) Sugar Spun Sister (Remastered),The Stone Roses,The Stone Roses,206000,0,1,NaN
4,0,(Stay Away From) The Cocaine Train,The Essential Johnny Paycheck,Johnny Paycheck,188000,0,2,NaN

,Unnamed: 0,Title,Album,Artist,Duration (ms),Rating,Play Count,Removed
4068,0,The Decision,NSFW,Ninja Sex Party,119000,5,72,NaN
4734,0,What I did for Love (feat. Emeli Sandé),Listen (Deluxe),David Guetta,207000,0,68,NaN
4936,0,You Make Me,True,Avicii,233000,0,68,NaN
172,0,Addicted To You,True,Avicii,148000,0,65,NaN
4323,0,Titanium (feat. Sia),Nothing But the Beat Ultimate,David Guetta - Sia,245000,0,62,NaN

238928.22228891557
229704.62515114874

In [3]:
import seaborn as sns

display(sns.distplot(combined_outliers_trimmed_df['Duration (ms)']))

In [4]:

grouped_df = google_listened_to_df.groupby(['Artist'], as_index=False)['Play Count'].sum()

grouped_indexed_df = google_listened_to_df.groupby(['Artist'], as_index=True)['Play Count'].sum()
grouped_indexed_df = grouped_indexed_df.sort_values(ascending=False)
display(grouped_indexed_df.head())

grouped_df = grouped_df.sort_values('Play Count', ascending=False)
# type(grouped_df)

display(grouped_df.head())

Artist
David Guetta       1150
Avicii             1138
Ninja Sex Party     840
Pink Floyd          646
Kidzone             477
Name: Play Count, dtype: int64

              Artist  Play Count
242     David Guetta        1150
87            Avicii        1138
577  Ninja Sex Party         840
633       Pink Floyd         646
465          Kidzone         477

In [ ]:
artist_input = input('Please choose Artist:')

In [ ]:
artist_specific_df = google_listened_to_df.loc[google_listened_to_df['Artist'] == artist_input]

display(artist_specific_df)

In [ ]:
plot = grouped_indexed_df.head().plot.pie(y='Artist')

In [ ]:
plot = grouped_indexed_df[:150].plot.pie(y='Artist')